### ISSUE TITLE
Requirement: Optional startup parameters

### ISSUE THREAD

**Issue by cyberphone** [browserext/native-messaging#5]
There may be reasons providing optional parameters to invoked applications that could affect rendering etc.

**Comment by aswan** [comment]
This description is awfully vague, can you elaborate?

**Comment by cyberphone** [comment]
Assume that there is a method <code>connect</code>(_native app id_) which invokes a native application. This method could have an optional JavaScript JSON serializable parameter which could affect how the native application renders etc.  That is, this parameters is application specific.

**Comment by frivoal** [comment]
**This is a tentative resolution of the CG. See the [minutes of the discussion](http://browserext.github.io/minutes/2016-09-09.html). If no dissenting opinion is expressed here within 10 days, this will be considered the consensus of the CG.**

This does not seem necessary, as it is already possible for the extension to communicate with the native app, and send any information it wants, at any time it wants, using any format that it wants. The tentative consensus is to reject the proposal.
